/*
 * Please add organization file header by setting property "fileHeaderCompany"
 *
 * All rights reserved.
 */
package com.anaptecs.jeaf.timetable.api;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import jakarta.validation.constraints.NotNull;
import tools.jackson.databind.annotation.JsonDeserialize;
import tools.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Data structure represents a technical problem that occurred during a REST call (aka as Problem JSON). It is
 * compatible with problem structure as it is defined in RFC7807 (https://datatracker.ietf.org/doc/html/rfc7807).<br/>
 * <br/>
 * Here, problems are only used to indicate technical problems. Business problems need to provide way more context and
 * thus will be part of response data structure.
 *
 * @author JEAF Generator
 * @version 1.0
 */
@JsonDeserialize(builder = Problem.Builder.class)
public class Problem {
  /**
   * Constant for the name of attribute "title".
   */
  public static final String TITLE = "title";

  /**
   * Constant for the name of attribute "status".
   */
  public static final String STATUS = "status";

  /**
   * Constant for the name of attribute "type".
   */
  public static final String TYPE = "type";

  /**
   * Constant for the name of attribute "detail".
   */
  public static final String DETAIL = "detail";

  /**
   * Constant for the name of attribute "instance".
   */
  public static final String INSTANCE = "instance";

  /**
   * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
   * problem, except for purposes of localization.<br/>
   * Consumers MUST use the &quot;type&quot; string as the primary identifier for the problem type; the
   * &quot;title&quot; string is advisory and included only for users who are not aware of the semantics of the URI and
   * do not have the ability to discover them.
   */
  @NotNull
  private final String title;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   */
  public final int status;

  /**
   * A URI reference [RFC3986] that identifies the problem type. When this member is not present, its value is assumed
   * to be &quot;about:blank&quot;. <br/>
   * <b>Default Value:</b> <code>"about:blank"</code>
   */
  @NotNull
  private final String type;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  @NotNull
  private final String detail;

  /**
   * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information
   * if dereferenced.
   */
  @NotNull
  private final String instance;

  /**
   * Initialize object using the passed builder.
   *
   * @param pBuilder Builder that should be used to initialize this object. The parameter must not be null.
   */
  protected Problem( Builder pBuilder ) {
    // Read attribute values from builder.
    title = pBuilder.title;
    status = pBuilder.status;
    type = pBuilder.type;
    detail = pBuilder.detail;
    instance = pBuilder.instance;
  }

  /**
   * Method returns a new builder.
   *
   * @return {@link Builder} New builder that can be used to create new Problem objects.
   */
  public static Builder builder( ) {
    return new Builder();
  }

  /**
   * Class implements builder to create a new instance of class <code>Problem</code>.
   */
  @JsonPOJOBuilder(withPrefix = "set")
  @JsonIgnoreProperties(ignoreUnknown = true)
  public static class Builder {
    /**
     * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization.<br/>
     * Consumers MUST use the &quot;type&quot; string as the primary identifier for the problem type; the
     * &quot;title&quot; string is advisory and included only for users who are not aware of the semantics of the URI
     * and do not have the ability to discover them.
     */
    private String title;

    /**
     * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
     */
    private int status;

    /**
     * A URI reference [RFC3986] that identifies the problem type. When this member is not present, its value is assumed
     * to be &quot;about:blank&quot;. <br/>
     * <b>Default Value:</b> <code>"about:blank"</code>
     */
    private String type = "about:blank";

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further
     * information if dereferenced.
     */
    private String instance;

    /**
     * Use {@link Problem#builder()} instead of private constructor to create new builder.
     */
    protected Builder( ) {
    }

    /**
     * Use {@link Problem#builder(Problem)} instead of private constructor to create new builder.
     */
    protected Builder( Problem pObject ) {
      if (pObject != null) {
        // Read attribute values from passed object.
        this.setTitle(pObject.title);
        this.setStatus(pObject.status);
        this.setType(pObject.type);
        this.setDetail(pObject.detail);
        this.setInstance(pObject.instance);
      }
    }

    /**
     * Method sets attribute {@link #title}.<br/>
     *
     * @param pTitle Value to which {@link #title} should be set.
     * @return {@link Builder} Instance of this builder to support chaining setters. Method never returns null.
     */
    @JsonSetter(nulls = Nulls.SKIP)
    public Builder setTitle( String pTitle ) {
      // Assign value to attribute
      title = pTitle;
      return this;
    }

    /**
     * Method sets attribute {@link #status}.<br/>
     *
     * @param pStatus Value to which {@link #status} should be set.
     * @return {@link Builder} Instance of this builder to support chaining setters. Method never returns null.
     */
    @JsonSetter(nulls = Nulls.SKIP)
    public Builder setStatus( int pStatus ) {
      // Assign value to attribute
      status = pStatus;
      return this;
    }

    /**
     * Method sets attribute {@link #type}.<br/>
     *
     * @param pType Value to which {@link #type} should be set.
     * @return {@link Builder} Instance of this builder to support chaining setters. Method never returns null.
     */
    @JsonSetter(nulls = Nulls.SKIP)
    public Builder setType( String pType ) {
      // Assign value to attribute
      type = pType;
      return this;
    }

    /**
     * Method sets attribute {@link #detail}.<br/>
     *
     * @param pDetail Value to which {@link #detail} should be set.
     * @return {@link Builder} Instance of this builder to support chaining setters. Method never returns null.
     */
    @JsonSetter(nulls = Nulls.SKIP)
    public Builder setDetail( String pDetail ) {
      // Assign value to attribute
      detail = pDetail;
      return this;
    }

    /**
     * Method sets attribute {@link #instance}.<br/>
     *
     * @param pInstance Value to which {@link #instance} should be set.
     * @return {@link Builder} Instance of this builder to support chaining setters. Method never returns null.
     */
    @JsonSetter(nulls = Nulls.SKIP)
    public Builder setInstance( String pInstance ) {
      // Assign value to attribute
      instance = pInstance;
      return this;
    }

    /**
     * Method creates a new instance of class Problem. The object will be initialized with the values of the builder.
     *
     * @return Problem Created object. The method never returns null.
     */
    public Problem build( ) {
      return new Problem(this);
    }
  }

  /**
   * Method returns attribute {@link #title}.<br/>
   * A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the
   * problem, except for purposes of localization.<br/>
   * Consumers MUST use the &quot;type&quot; string as the primary identifier for the problem type; the
   * &quot;title&quot; string is advisory and included only for users who are not aware of the semantics of the URI and
   * do not have the ability to discover them.
   *
   * @return {@link String} Value to which {@link #title} is set.
   */
  public String getTitle( ) {
    return title;
  }

  /**
   * Method returns attribute {@link #status}.<br/>
   * The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   *
   * @return int Value to which {@link #status} is set.
   */
  public int getStatus( ) {
    return status;
  }

  /**
   * Method returns attribute {@link #type}.<br/>
   * A URI reference [RFC3986] that identifies the problem type. When this member is not present, its value is assumed
   * to be &quot;about:blank&quot;.
   *
   * @return {@link String} Value to which {@link #type} is set.
   */
  public String getType( ) {
    return type;
  }

  /**
   * Method returns attribute {@link #detail}.<br/>
   * A human-readable explanation specific to this occurrence of the problem.
   *
   * @return {@link String} Value to which {@link #detail} is set.
   */
  public String getDetail( ) {
    return detail;
  }

  /**
   * Method returns attribute {@link #instance}.<br/>
   * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information
   * if dereferenced.
   *
   * @return {@link String} Value to which {@link #instance} is set.
   */
  public String getInstance( ) {
    return instance;
  }

  @Override
  public int hashCode( ) {
    final int lPrime = 31;
    int lResult = 1;
    lResult = lPrime * lResult + Objects.hashCode(title);
    lResult = lPrime * lResult + status;
    lResult = lPrime * lResult + Objects.hashCode(type);
    lResult = lPrime * lResult + Objects.hashCode(detail);
    lResult = lPrime * lResult + Objects.hashCode(instance);
    return lResult;
  }

  @Override
  public boolean equals( Object pObject ) {
    boolean lEquals;
    if (this == pObject) {
      lEquals = true;
    }
    else if (pObject == null) {
      lEquals = false;
    }
    else if (this.getClass() != pObject.getClass()) {
      lEquals = false;
    }
    else {
      Problem lOther = (Problem) pObject;
      lEquals = Objects.equals(title, lOther.title) && status == lOther.status && Objects.equals(type, lOther.type)
          && Objects.equals(detail, lOther.detail) && Objects.equals(instance, lOther.instance);
    }
    return lEquals;
  }

  /**
   * Method returns a StringBuilder that can be used to create a String representation of this object. The returned
   * StringBuilder also takes care about attributes of super classes.
   *
   * @return {@link StringBuilder} StringBuilder representing this object. The method never returns null.
   */
  public StringBuilder toStringBuilder( String pIndent ) {
    StringBuilder lBuilder = new StringBuilder();
    lBuilder.append(pIndent);
    lBuilder.append(this.getClass().getName());
    lBuilder.append(System.lineSeparator());
    lBuilder.append(pIndent);
    lBuilder.append("title: ");
    lBuilder.append(title);
    lBuilder.append(System.lineSeparator());
    lBuilder.append(pIndent);
    lBuilder.append("status: ");
    lBuilder.append(status);
    lBuilder.append(System.lineSeparator());
    lBuilder.append(pIndent);
    lBuilder.append("type: ");
    lBuilder.append(type);
    lBuilder.append(System.lineSeparator());
    lBuilder.append(pIndent);
    lBuilder.append("detail: ");
    lBuilder.append(detail);
    lBuilder.append(System.lineSeparator());
    lBuilder.append(pIndent);
    lBuilder.append("instance: ");
    lBuilder.append(instance);
    lBuilder.append(System.lineSeparator());
    return lBuilder;
  }

  /**
   * Method creates a new String with the values of all attributes of this class. All references to other objects will
   * be ignored.
   *
   * @return {@link String} String representation of this object. The method never returns null.
   */
  @Override
  public String toString( ) {
    return this.toStringBuilder("").toString();
  }

  /**
   * Method creates a new builder and initializes it with the data of this object.
   *
   * @return {@link Builder} New builder that can be used to create new Problem objects. The method never returns null.
   */
  public Builder toBuilder( ) {
    return new Builder(this);
  }
}